starting-region: Varlamore
starting-location: Civitas illa Fortis

always-accessible:
  - Varlamore
  - Karamja

unlockable-regions:
  - Asgarnia
  - Fremennik
  - Kandarin
  - Desert
  - Morytania
  - Tirannwn
  - Wilderness
  - Kourend

max-region-unlocks: 3

starting-skills:
  Herblore: 3
  Runecraft: 5

autocompleted-quests:
  - Dragon Slayer I
  - Learning the Ropes
  - The Restless Ghost
  - Rune Mysteries
  - Children of the Sun
  - Desert Treasure II - The Fallen Empire
  - Druidic Ritual
  - Eagles' Peak
  - Elemental Workshop I
  - Fairytale I - Growing Pains
  - Fairytale II - Cure a Queen
  - Lost City
  - Nature Spirit
  - Perilous Moons
  - Priest in Peril
  - Twilight's Promise
